### PR TITLE
Print degrees with correct symbol

### PR DESCRIPTION
**Pull request by arinbjornk**
Use degree symbol instead of apostrophe when printing temperature units.

Example:
40°C instead of 40'C

### CODE REVIEW

**Comment by wookayin** [comment]
Test is failing. You should:

* Add `-*- encoding: utf-8 -*-` magic to deal with python 2.
* Expected output in test cases should be modified accordingly.

**Comment by Stonesjtu** [comment]
Try using the first style, should be supported natively by python, https://stackoverflow.com/a/35615110 .

**Comment by wookayin** [comment]
@arinbjornk Would you be interested in finishing this? Still, test is failing because of python2 and it is a little bit tricky to completely fix it.

**Comment by arinbjornk** [comment]
I would like to but unfortunately I haven't had the time to fix the python 2 issue. Are you planning python 2 support for the foreseeable future?

**Comment by wookayin** [comment]
Well, I am happy with dropping python2 support and we already have a reasonably good version of gpustat that works well with python2. I'll take a look at this again sometime later to see any chance.

**Comment by Stonesjtu** [comment]
@arinbjornk Since we are dropping python2 now so probably you can just revert the recent commits on dealing with python2.

**Comment by wookayin** [comment]
Rebased, and squash-merged as 6d2b1d0.

**Pull request closed without merging**
