### PR TITLE
Stop supporting Python 2

### LINKED ISSUE #66: Drop Python 2 Support
@Stonesjtu [Pointed out that Python 2 is being retired](https://github.com/wookayin/gpustat/pull/65#issuecomment-512323532):

> python2.7 is retiring in Jan 1st 2020, so probably the master branch can focus on only python 3.
Ref. https://pythonclock.org/

> According to https://stackoverflow.com/questions/40114100/uploading-different-versions-python-2-7-vs-3-5-to-pypi, we can simply add python_requires='>=3.4' and bump the version.
Then if you install the package via pip2, the out-dated one instead of the newest version will be selected.

### PR DESCRIPTION
**Pull request by bethune-bryant**
Fixes #66.

Python 2 is being retired. This change should remove support for it going forward, but if a user still wants to use Python 2 they would just get the older version.

### CODE REVIEW

**Comment by bethune-bryant** [comment]
@Stonesjtu 
Do you know if there are there any other changes required for this?

**Comment by Stonesjtu** [comment]
Afaik, it should work. @wookain plz tag the current master as the final python2 support (optionally a final version on pypi) , then test this PR via a new version upload.

After that we can try install the package using different pip, see if it automatically choose the right version.

**Comment by wookayin** [comment]
Speaking of retiring python2, I think this would be the best time to version our gpustat finally as 1.0.

**Comment by Stonesjtu** [comment]
@wookayin I think we can merge this and #65 now.

**Comment by wookayin** [comment]
Merged as fd337b9 (manually rebased and squashed due to conflict)

**Pull request closed without merging**
